"""Reusable UI components. HTML-producing helpers return `Html` (already safe); everything else is escaped."""
from __future__ import annotations

import html
import math
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any

import streamlit as st

from lifeline.constants import LOW_UNITS
from lifeline.engine.sorting import merge_sort
from lifeline.services.stock import group_level
from lifeline.ui import tokens as t
from lifeline.ui.theme import current_theme


class Html(str):
    """Markup generated by this module (already escaped where it embeds data)."""


def esc(value: object) -> str:
    return str(value) if isinstance(value, Html) else html.escape("" if value is None else str(value))


def _flat(markup: str) -> Html:
    """Markdown ends an HTML block at a blank line and turns indented lines after it into code: strip both."""
    return Html("\n".join(line for line in (raw.strip() for raw in markup.splitlines()) if line))


def render(markup: str) -> None:
    st.markdown(markup, unsafe_allow_html=True)


# ------------------------------------------------------------------ status + badges
_KIND = {
    "danger": ("CRITICAL", "SEVERE", "BLOCK", "BREACHED", "REJECTED", "HIGH", "LAPSED", "OVERDUE"),
    "warning": ("URGENT", "MODERATE", "MILD", "DEFER", "UNKNOWN", "MEDIUM", "RESERVED", "ACCEPTED"),
    "success": ("ROUTINE", "RESOLVED", "ACTIVE", "SAFE", "NONE", "LOW", "RETURNED", "COMPLETED", "CORE", "OK", "AVAILABLE"),
    "info": ("PENDING", "OCCASIONAL"),
}
STATUS_KIND = {label: kind for kind, labels in _KIND.items() for label in labels}
MARKS = {"danger": "▲", "warning": "◆", "success": "✓", "info": "●", "neutral": "○"}     # a shape cue as well as a colour


def status_pill(status: str, label: str | None = None, kind: str | None = None) -> Html:
    kind = kind or STATUS_KIND.get(str(status).upper(), "neutral")
    fg, bg, border = t.kind_style(kind, current_theme())
    text = esc(label if label is not None else str(status).replace("_", " "))
    return Html(f'<span class="ll-pill" data-mark="{MARKS[kind]}" style="color:{fg};background:{bg};border-color:{border}">{text}</span>')


def blood_group_badge(group: str, units: int | None = None) -> Html:
    """The group is always printed. Rh-positive badges are filled, Rh-negative ones outlined (a cue that is not colour)."""
    if group not in t.BLOOD_HUE_KEYS:
        return Html(f'<span class="ll-badge" style="color:inherit;border-color:currentColor">{esc(group)}</span>')
    fg, bg, border, filled = t.blood_style(group, current_theme())
    suffix = f" · {int(units)}u" if units is not None else ""
    return Html(f'<span class="ll-badge" style="color:{fg};background:{bg};border-color:{border}"'
                f' title="{"Rh positive" if filled else "Rh negative"}">{esc(group)}{suffix}</span>')


def level_pill(level: str) -> Html:
    return status_pill(level, label=level.upper(), kind={"critical": "danger", "low": "warning", "ok": "success"}[level])


# ------------------------------------------------------------------ cards, alerts, sections
def kpi_card(label: str, value: object, *, hint: str = "", tone: str = "neutral") -> Html:
    hint_html = f'<div class="ll-kpi-hint">{esc(hint)}</div>' if hint else ""
    return _flat(f'<div class="ll-kpi tone-{tone}"><div class="ll-kpi-label">{esc(label)}</div>'
                 f'<div class="ll-kpi-value">{esc(value)}</div>{hint_html}</div>')


def kpi_row(*cards: Html) -> None:
    render(_flat('<div class="ll-kpis">' + "".join(cards) + "</div>"))


_ALERT_ICON = {"info": "ℹ", "success": "✓", "warning": "◆", "danger": "▲"}
_ALERT_TITLE = {"info": "Info", "success": "Done", "warning": "Check", "danger": "Problem"}


def alert_html(message: str, level: str = "info", title: str | None = None) -> Html:
    role = "alert" if level in ("danger", "warning") else "status"
    return _flat(f'<div class="ll-alert {level}" role="{role}"><span aria-hidden="true">{_ALERT_ICON[level]}</span>'
                 f'<div><b>{esc(title or _ALERT_TITLE[level])}:</b> {esc(message)}</div></div>')


def alert_banner(message: str, level: str = "info", title: str | None = None) -> None:
    render(alert_html(message, level, title))


def empty_state(title: str, body: str = "", icon: str = "○") -> None:
    body_html = f"<p>{esc(body)}</p>" if body else ""
    render(_flat(f'<div class="ll-empty"><div class="ll-empty-icon" aria-hidden="true">{esc(icon)}</div><h4>{esc(title)}</h4>{body_html}</div>'))


def section_header(title: str, subtitle: str = "") -> None:
    sub = f"<span>{esc(subtitle)}</span>" if subtitle else ""
    render(_flat(f'<div class="ll-section"><h3>{esc(title)}</h3>{sub}</div>'))


def steps(labels: Sequence[str], current: int) -> None:
    items = []
    for i, label in enumerate(labels, start=1):
        state = "active" if i == current else "done" if i < current else ""
        mark = "✓" if i < current else str(i)
        items.append(f'<div class="ll-step {state}" {"aria-current=step" if i == current else ""}><i>{mark}</i>{esc(label)}</div>')
    render(_flat('<div class="ll-steps">' + "".join(items) + "</div>"))


def ai_panel(text: str) -> None:
    """Every AI answer is labelled as advisory. The deterministic engine result stays the source of truth."""
    render(_flat(f'<div class="ll-ai"><span class="ll-ai-label">AI suggestion — verify clinically</span>'
                 f'<div class="ll-ai-body">{esc(text)}</div></div>'))


# ------------------------------------------------------------------ stock grid
def stock_grid(counts: Mapping[str, int], groups: Sequence[str] = t.BLOOD_HUE_KEYS) -> Html:
    """Eight cards, one per group: the count, a level word + glyph (not colour alone) and a proportional bar."""
    scale = max(LOW_UNITS * 3, max(counts.values(), default=0))
    palette = t.palette(current_theme())
    colours = {"critical": palette.danger, "low": palette.warning, "ok": palette.success}
    cards = []
    for group in groups:
        n = int(counts.get(group, 0))
        level = group_level(n)
        pct = min(100, round(n / scale * 100))
        cards.append(
            f'<div class="ll-stock {level}"><div class="ll-stock-head">{blood_group_badge(group)}{level_pill(level)}</div>'
            f'<div class="ll-stock-count">{n}<small>units</small></div>'
            f'<div class="ll-bar" role="img" aria-label="{n} units, {level}"><i style="width:{pct}%;background:{colours[level]}"></i></div></div>')
    return _flat('<div class="ll-stock-grid">' + "".join(cards) + "</div>")


def row_list(rows: Sequence[tuple[Html | str, Html | str]], empty: str = "Nothing to show") -> Html:
    """A compact two-column list (left text/badge, right meta) for dashboard panels."""
    if not rows:
        return _flat(f'<div class="ll-row"><span class="meta">{esc(empty)}</span></div>')
    return _flat('<div class="ll-list">' + "".join(
        f'<div class="ll-row"><span>{esc(left)}</span><span class="meta">{esc(right)}</span></div>' for left, right in rows) + "</div>")


# ------------------------------------------------------------------ data table
@dataclass(frozen=True)
class Col:
    label: str
    field: str
    render: Callable[[Any, Mapping[str, Any]], Any] | None = None    # cell renderer (may return Html)
    align: str = "left"
    sortable: bool = True
    search: bool = True


@dataclass(frozen=True)
class TableView:
    rows: list[Mapping[str, Any]]
    total: int          # rows after filtering
    page: int
    pages: int


def _sort_key(field: str) -> Callable[[Mapping[str, Any]], tuple[int, str, float]]:
    def key(row: Mapping[str, Any]) -> tuple[int, str, float]:
        value = row.get(field)
        if value is None:
            return (2, "", 0.0)                                          # missing values sort last
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return (0, "", float(value))
        return (1, str(value).lower(), 0.0)

    return key


def table_view(rows: Sequence[Mapping[str, Any]], cols: Sequence[Col], *, query: str = "", sort_field: str | None = None,
               descending: bool = False, page: int = 1, page_size: int = 10) -> TableView:
    """Search, sort and paginate (pure function: this is what the widget wraps)."""
    q = query.strip().lower()
    found = [r for r in rows if not q or any(q in str(r.get(c.field, "")).lower() for c in cols if c.search)]
    if sort_field:
        present = [r for r in found if r.get(sort_field) is not None]
        missing = [r for r in found if r.get(sort_field) is None]                     # missing values stay last in both directions
        found = merge_sort(present, key=_sort_key(sort_field), reverse=descending) + missing   # stable: equal rows keep their order
    pages = max(1, math.ceil(len(found) / page_size))
    page = min(max(1, page), pages)
    return TableView(found[(page - 1) * page_size: page * page_size], len(found), page, pages)


def html_table(rows: Sequence[Mapping[str, Any]], cols: Sequence[Col], caption: str = "") -> Html:
    head = "".join(f'<th scope="col"{" class=num" if c.align == "right" else ""}>{esc(c.label)}</th>' for c in cols)
    body = []
    for row in rows:
        cells = []
        for c in cols:
            value = row.get(c.field)
            shown = c.render(value, row) if c.render else value
            cells.append(f'<td{" class=num" if c.align == "right" else ""}>{esc("—" if shown in (None, "") else shown)}</td>')
        body.append("<tr>" + "".join(cells) + "</tr>")
    cap = f"<caption>{esc(caption)}</caption>" if caption else ""
    return _flat(f'<div class="ll-table-wrap"><table class="ll-table">{cap}<thead><tr>{head}</tr></thead>'
                 f'<tbody>{"".join(body)}</tbody></table></div>')


def data_table(rows: Sequence[Mapping[str, Any]], cols: Sequence[Col], *, key: str, page_size: int = 10,
               empty_title: str = "Nothing here yet", empty_body: str = "", default_sort: str | None = None) -> None:
    """A table with search, sort and pagination. State is kept per `key`; text is escaped unless a renderer returns Html."""
    if not rows:
        empty_state(empty_title, empty_body)
        return
    sortable = [c for c in cols if c.sortable]
    controls = len(rows) > page_size or len(rows) > 6
    query, sort_label, descending = "", "Default order", False
    if controls:
        c1, c2, c3 = st.columns([3, 2, 2])
        query = c1.text_input("Search", key=f"{key}:q", placeholder="Search this table")
        sort_label = c2.selectbox("Sort by", ["Default order"] + [c.label for c in sortable], key=f"{key}:sort")
        descending = c3.selectbox("Order", ["Ascending", "Descending"], key=f"{key}:dir") == "Descending"
    field = next((c.field for c in sortable if c.label == sort_label), default_sort)
    page = int(st.session_state.get(f"{key}:page", 1))
    view = table_view(rows, cols, query=query, sort_field=field, descending=descending, page=page, page_size=page_size)
    render(html_table(view.rows, cols, caption=f"{view.total} row{'s' if view.total != 1 else ''}") if view.total else
           _flat('<div class="ll-empty"><h4>No matching rows</h4><p>Try a different search.</p></div>'))
    if view.pages > 1:
        b1, b2, b3 = st.columns([1, 2, 1])
        if b1.button("‹ Previous", key=f"{key}:prev", disabled=view.page <= 1):
            st.session_state[f"{key}:page"] = view.page - 1
            st.rerun()
        b2.markdown(f"<div style='text-align:center;padding-top:10px'>Page {view.page} of {view.pages}</div>", unsafe_allow_html=True)
        if b3.button("Next ›", key=f"{key}:next", disabled=view.page >= view.pages):
            st.session_state[f"{key}:page"] = view.page + 1
            st.rerun()
    else:
        st.session_state[f"{key}:page"] = 1


# ------------------------------------------------------------------ confirmation
def confirm_dialog(key: str, label: str, prompt: str, *, confirm_label: str = "Confirm", danger: bool = False,
                   disabled: bool = False) -> bool:
    """Two-step control for destructive or clinical actions. Shows `label`; once clicked it asks `prompt` and offers
    Confirm / Cancel. Returns True exactly once, on the run right after the user confirms (the first button is shown again)."""
    asking, confirmed = f"confirm:{key}", f"confirmed:{key}"
    done = bool(st.session_state.pop(confirmed, False))
    if not st.session_state.get(asking):
        if st.button(label, key=f"{key}:ask", disabled=disabled):
            st.session_state[asking] = True
            st.rerun()
        return done
    alert_banner(prompt, "danger" if danger else "warning", title="Please confirm")
    yes, no = st.columns(2)
    if yes.button(confirm_label, key=f"{key}:yes", type="primary"):
        st.session_state[asking] = False
        st.session_state[confirmed] = True
        st.rerun()
    if no.button("Cancel", key=f"{key}:no"):
        st.session_state[asking] = False
        st.rerun()
    return False


def field_error(message: str | None) -> None:
    """Inline validation message shown directly under the field it belongs to."""
    if message:
        render(_flat(f'<div class="ll-alert danger" role="alert" style="margin-top:-4px;padding:6px 12px"><div>{esc(message)}</div></div>'))
